CREATE TABLE IF NOT EXISTS Account (
  UserId INTEGER PRIMARY KEY AUTOINCREMENT,
  UserName TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UserImg TEXT,
  LastLogin DATETIME,
  UsedCapacity INTEGER,
  Capacity INTEGER
);